### ISSUE TITLE
CreateRequestOptions

### ISSUE THREAD

**Issue by melihekmekci** [smartface/sf-extension-mcs#2]
Merhaba, Oracle MCS'den custom API' a ulaşmak için sanırım createRequestOptions'ı kullanıyoruz. Birtane örnek ile açıklayabilir misiniz? Bu API'ye ulaşmak için öncesinde mcs.login ile işlem yapmam gerekiyor mu? Yoksa direk bu createRequestOptions'ın içinde halledebiliyor muyuz?

**Comment by alperozisik** [comment]
first [configure](https://github.com/smartface/sf-extension-mcs#how-to-use) your mcs 
Checkout [http](http://ref.smartface.io/#!/api/Net.Http)
```javascript
var options = Object.assign(mcs.createRequestOptions({
 apiName: "apiName",
 endpointPath: "path"
}), {
 onLoad: function(response) {
   //success case
 },
 onError: function(error) {
  //negative path
 }
});
http.request(options);
```
